# Generated by Django 3.0.2 on 2020-01-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('type', models.CharField(max_length=10)),
                ('plate_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='plate_num',
            field=models.ForeignKey(blank=True, db_column='plate_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ride_Share.Vehicle'),
        ),
    ]
