# Generated by Django 3.0.2 on 2020-01-28 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0002_auto_20200128_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('dest', models.CharField(max_length=100)),
                ('pickup_time', models.DateTimeField()),
                ('owner_pass_num', models.IntegerField()),
                ('actual_pass_num', models.IntegerField()),
                ('ride_status', models.CharField(max_length=10)),
                ('sharable', models.BooleanField()),
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ride',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('sharerid', models.OneToOneField(db_column='sharerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pass_num', models.IntegerField()),
                ('rideid', models.ForeignKey(db_column='rideid', on_delete=django.db.models.deletion.DO_NOTHING, to='Ride_Share.Ride')),
            ],
            options={
                'db_table': 'sharer',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver2id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner2id', to=settings.AUTH_USER_MODEL),
        ),
    ]
