# Generated by Django 3.0.2 on 2020-01-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0003_auto_20200128_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='myuser',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
