# Generated by Django 2.2.9 on 2020-01-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0004_auto_20200128_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='myuser',
            table=None,
        ),
    ]
