# Generated by Django 2.2.9 on 2020-01-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0006_auto_20200129_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('ava', 'Available'), ('con', 'Confirmed'), ('cop', 'Completed')], default='ava', max_length=10),
        ),
    ]
