# Generated by Django 2.2.9 on 2020-01-30 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0007_auto_20200130_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, db_column='driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver2id', to=settings.AUTH_USER_MODEL),
        ),
    ]
