# Generated by Django 2.2.9 on 2020-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0008_auto_20200130_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('opn', 'Open'), ('con', 'Confirmed'), ('cop', 'Completed')], default='ava', max_length=10),
        ),
    ]
