# Generated by Django 2.2.9 on 2020-01-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0010_auto_20200131_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
