# Generated by Django 2.2.9 on 2020-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0014_auto_20200131_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='dest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='earliest_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sharer',
            name='latest_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='pass_num',
            field=models.IntegerField(null=True),
        ),
    ]
