# Generated by Django 2.2.9 on 2020-01-31 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0016_auto_20200131_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='sharerid',
            field=models.OneToOneField(db_column='sharerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
