# Generated by Django 2.2.9 on 2020-01-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0017_auto_20200131_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='avail_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('con', 'Convertible'), ('cou', 'Coupe'), ('sed', 'Sedan'), ('suv', 'SUV'), ('tru', 'Truck')], max_length=10, null=True),
        ),
    ]
