# Generated by Django 2.2.9 on 2020-02-01 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0019_auto_20200201_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='rideid',
        ),
        migrations.AddField(
            model_name='ride',
            name='share_id',
            field=models.ForeignKey(blank=True, db_column='sharer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ride_Share.Sharer'),
        ),
    ]
