# Generated by Django 2.2.9 on 2020-02-02 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0020_auto_20200201_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='share_id',
            field=models.ForeignKey(blank=True, db_column='sharer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegisteredSharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_sharer_id', models.ForeignKey(db_column='joined_sharer_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
