# Generated by Django 2.2.9 on 2020-02-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0026_auto_20200203_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('opn', 'Open'), ('con', 'Confirmed'), ('cop', 'Completed')], default='opn', max_length=10),
        ),
    ]
