# Generated by Django 2.2.9 on 2020-02-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0028_auto_20200204_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsharer',
            name='rideid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ride_Share.Ride'),
        ),
    ]
