# Generated by Django 2.2.9 on 2020-02-05 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0029_auto_20200204_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsharer',
            name='registered_sharer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
