# Generated by Django 2.2.9 on 2020-02-05 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0030_auto_20200204_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='share_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='share_id',
            field=models.ManyToManyField(blank=True, db_column='sharer', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
