# Generated by Django 2.2.9 on 2020-02-05 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0031_auto_20200205_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='share_id',
            field=models.ManyToManyField(blank=True, db_column='sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
