# Generated by Django 2.2.9 on 2020-02-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0033_registeredsharer_pass_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_requests',
            field=models.TextField(default='', max_length=140),
        ),
    ]
