# Generated by Django 2.2.9 on 2020-02-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0034_ride_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='special_requests',
            field=models.TextField(default='', max_length=140),
        ),
    ]
