# Generated by Django 2.2.9 on 2020-02-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0035_sharer_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('con', 'Convertible'), ('cou', 'Coupe'), ('sed', 'Sedan'), ('suv', 'SUV'), ('tru', 'Truck')], max_length=20),
        ),
    ]
