# Generated by Django 2.2.9 on 2020-02-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0036_auto_20200206_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('con', 'Convertible'), ('cou', 'Coupe'), ('sed', 'Sedan'), ('suv', 'SUV'), ('tru', 'Truck')], max_length=10),
        ),
    ]
