# Generated by Django 2.2.9 on 2020-02-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0037_auto_20200206_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_vehicle_info',
            field=models.TextField(default='', max_length=140),
        ),
    ]
