# Generated by Django 2.2.9 on 2020-02-08 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0038_auto_20200207_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
