# Generated by Django 2.2.9 on 2020-02-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride_Share', '0039_vehicle_vehicle_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_owner_id',
        ),
    ]
